version: '3'
services:
  api:
    image: authentication_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "6500:5432"
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
volumes:
  progresDB:
     
